[package]
name = "tfrp"
version = "0.1.0"
authors = ["Jack Shih <i@kshih.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
env_logger = "*"
chrono = "*"
tokio = {version="*", features=["full"]}
ring = "*"
bytes = "*"
serde = {version="*", features=["derive"]}
clap = { git = "https://gitee.com/useptonly/clap.git" }
toml = "*"
futures = "*"
futures-util = "*"
hyper = "*"
headers = "*"
hyper-tls = "*"
tungstenite = "*"
tokio-tungstenite = "*"

[dev-dependencies]


[lib]
name = "tfrp"
path = "src/lib.rs"

[[bin]]
name = "tfrps"
path = "src/bin/server.rs"

[[bin]]
name = "tfrpc"
path = "src/bin/client.rs"
