[package]
name = "tfrp"
version = "0.1.0"
authors = ["Jack Shih <i@kshih.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
env_logger = "*"
chrono = "*"
async-std = {version="*", features=["attributes"]}
ring = "*"
bytes = "*"
serde = {version="*", features=["derive"]}
clap = { git = "https://gitee.com/useptonly/clap/" }
toml = "*"
futures = "*"

[dev-dependencies]


[lib]
name = "frp"
path = "src/lib.rs"

[[bin]]
name = "frps"
path = "src/bin/server.rs"

[[bin]]
name = "frpc"
path = "src/bin/client.rs"
