on: [push, pull_request]

name: CI

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: test
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin tfrps --release
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin tfrpc --release
  coverage:
    name: Coverage
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install LLVM11
        run: |
          curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository -y 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main'
          sudo apt-get install -y clang-11
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          default: true
      - name: Install golang toolchain
        uses: actions/setup-go@v2
        with:
          go-version: "1.14"
      - name: Install dependencies
        run: sudo apt-get install llvm llvm-7 libclang-common-7-dev llvm-7-dev
      - name: Build lcov
        run: admin/build-lcov
      - name: Measure coverage
        run: admin/coverage
      - name: Report to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: final.info
          fail_ci_if_error: false